### ISSUE TITLE
Rescript v11 support

### ISSUE THREAD

**Issue by DZakh** [rescript-labs/decco#93]
I got the following compile error `Error: "Decco" in public is not an existing module `:
<img width="1212" alt="image" src="https://github.com/reasonml-labs/decco/assets/49292466/7cfdb590-8937-42f1-955d-66299e3d74a6">

**Comment by mrmurphy** [comment]
Will be closed by #94 when I get the GitHub actions working again

**Comment by mrmurphy** [comment]
@DZakh Version 2.0.0 (available on NPM as `@rescript-labs/decco`) supports Rescript 11
